CREATE TABLE IF NOT EXISTS users (
    uid UUID DEFAULT gen_random_uuid(),
    sub TEXT NOT NULL,
    vpa TEXT NULL,
    last_add TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (uid),
    UNIQUE (sub)
);

CREATE INDEX IF NOT EXISTS users_vpa ON users (vpa);
