services:
  db:
    image: 'postgres:16-alpine3.19'
    expose:
      - '5432'
    volumes:
      - 'psql:/var/lib/postgresql/data:Z'
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: fairshare
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres", "--dbname=fairshare"]
  api:
    build: .
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - database
      - backend
    depends_on:
      db:
        required: true
        condition: service_healthy
      kc:
        required: true
        condition: service_healthy
    environment:
      FAIRSHARE_DB: 'postgres://postgres:secret@db:5432/fairshare?sslmode=disable'
      FAIRSHARE_AUTH: 'http://kc:8080/realms/fairshare'
      FAIRSHARE_AUDIENCE: account
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
  kc:
    build:
      dockerfile: ./keycloak.Dockerfile
    ports:
      - '9090:8080'
    expose:
      - '8080'
    volumes:
      - 'kc:/opt/keycloak/data:Z'
    networks:
      - backend
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health/ready"]

networks:
  database:
  backend:

volumes:
  kc:
  psql:
