name: commitlint(push)

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: 'Install required dependencies'
        run: npm ci
      - name: 'Validate current commit (last commit) with commitlint'
        run: npx commitlint --from HEAD~1 --to HEAD -q
