name: Go Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64, '386']
        exclude:
          - os: darwin
            arch: '386'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build {{ matrix.os }}-{{ matrix.arch }}
        run: GOOS={{ matrix.os }} GOARCH={{ matrix.arch }} go build .
